### ISSUE TITLE
Holiday data enhancement

### ISSUE THREAD

**Issue by kiwiflydream** [guangrei/Json-Indonesia-holidays#11]
<img width="436" alt="CleanShot 2023-05-19 at 18 08 05@2x" src="https://github.com/guangrei/Json-Indonesia-holidays/assets/13311001/04170372-6f10-413f-846c-ea576ea6ff9c">

<img width="580" alt="CleanShot 2023-05-19 at 18 08 27@2x" src="https://github.com/guangrei/Json-Indonesia-holidays/assets/13311001/e1ebb898-d226-4c60-a5c2-e849b2a81362">

**Comment by kiwiflydream** [comment]
https://www.kemenkopmk.go.id/sites/default/files/pengumuman/2022-10/SKB%20LibNas%20dan%20CuBer%202023_0.pdf

There are 32 days in the JSON, but there should only be 24 days.

**Comment by guangrei** [comment]
> https://www.kemenkopmk.go.id/sites/default/files/pengumuman/2022-10/SKB%20LibNas%20dan%20CuBer%202023_0.pdf
> 
> There are 32 days in the JSON, but there should only be 24 days.

hi, json data is always update automatically from google calendar 
and the data your provide is outdated (see screenshots below)
![Uploading snapshot_search_1684501847451.png…]()

**Comment by guangrei** [comment]
![Uploading snapshot_search_1684501847451.png…]()

**Comment by guangrei** [comment]
something went wrong when i tried to upload the screenshot, so i pasted the information directly
`Cuti bersama Lebaran 2023 yang semula hanya empat hari pada tanggal 21, 24, 25, dan 26 April 2023 diubah dan menjadi lima hari pada 19, 20, 21, 24, dan 25 April 2023`

**Comment by kiwiflydream** [comment]
Thank you very much for your reply, you are right.

**Comment by kiwiflydream** [comment]
![CleanShot 2023-05-20 at 09 55 40@2x](https://github.com/guangrei/Json-Indonesia-holidays/assets/13311001/0b1b2786-f89b-4509-9c56-9853272f10f5)

If following this, then the 21st should also be a holiday.

> something went wrong when i tried to upload the screenshot, so i pasted the information directly上传截图的时候出了点问题，直接贴上信息 `Cuti bersama Lebaran 2023 yang semula hanya empat hari pada tanggal 21, 24, 25, dan 26 April 2023 diubah dan menjadi lima hari pada 19, 20, 21, 24, dan 25 April 2023`

**Comment by guangrei** [comment]
> ![CleanShot 2023-05-20 at 09 55 40@2x](https://user-images.githubusercontent.com/13311001/239662254-0b1b2786-f89b-4509-9c56-9853272f10f5.png)
> 
> If following this, then the 21st should also be a holiday.
> 
> > something went wrong when i tried to upload the screenshot, so i pasted the information directly上传截图的时候出了点问题，直接贴上信息 `Cuti bersama Lebaran 2023 yang semula hanya empat hari pada tanggal 21, 24, 25, dan 26 April 2023 diubah dan menjadi lima hari pada 19, 20, 21, 24, dan 25 April 2023`

i see, in April there is more than one event (hari Kartini & Cuti Bersama Idul Fitri). for now this is a issue and i will try to fix it later

**Comment by guangrei** [comment]
@kiwiflydream check https://github.com/guangrei/APIHariLibur_V2

**Comment by kiwiflydream** [comment]
> @kiwiflydream check https://github.com/guangrei/APIHariLibur_V2 @kiwiflydream 检查 https://github.com/guangrei/APIHariLibur_V2

thank you, very much
