### ISSUE TITLE
Butuh calendar.json yang sudah minified

### ISSUE THREAD

**Issue by lakuapik** [guangrei/Json-Indonesia-holidays#3]
Halo bung,

Saya lihat repo https://github.com/guangrei/phptanggalmerah sumber calendarnya dari repo ini, dan saya lihat dia melakukan network request ke file `calendar.json`.

Sebaiknya file yang di call yang sudah di minified untuk menghemat traffic.

**Comment by guangrei** [comment]
Format json sengaja pretty print agar mudah dibaca terutama pada commit history, mungkin nanti di script phpnya  perlu ditambahkan fungsi cache

**Comment by lakuapik** [comment]
setuju, bisa juga dr php yang cache filenya.

PR ini sebenarnya nambah 1 file, `calendar.min.json`. Jadi kalau ada keperluan yg membutuhkan `calendar.json` yang prettify, tetap ada. Dan yang butuh minify, bisa pake yang `calendar.min.json`.

**Comment by guangrei** [comment]
Oh iya tp saya tidak bisa merge pr karena `calendar.json` digenerate otomatis.
mungkin nanti akan digenerate yg versi mhn juga tp untuk sekarang saya
tidak bisa ngoding atau login keserver tempat program berjalan.

**Comment by lakuapik** [comment]
Cek PR baru #6, generate otomatis saat push ke repo.

**Comment by guangrei** [comment]
> Cek PR baru #6, generate otomatis saat push ke repo.
 maaf bru merge sekarang, anyway thx

**Comment by guangrei** [comment]
maaf bru merge sekarang, anyway thx
